name: 'lint on merge request'

on:
  pull_request:
    branches:
      - master

jobs:
  job_lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: actions/setup-go@v4
    - name: 'Installing requirements'
      run: |
        rm -f README.md
        mv content/* .
        mv etc/* .
        npm install
    - name: 'Test build distributable files'
      run: |
        npm run build
