name: 'lint on merge request'

on:
  pull_request:
    branches:
      - master

jobs:
  job_lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 11
        check-latest: true
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: 'Installing requirements'
      run: npm install -g gitbook-cli
    - name: 'Generating distributable files'
      run: |
        mv content/* .
        mv etc/* .
        gitbook install
        gitbook build
